### ISSUE TITLE
Open source

### ISSUE THREAD

**Issue by PaulLeCam** [hailocab/grunt-crowdin#1]
- [x] Cleanup
- [x] Code review
- [x] Test with other project(s)
- [x] Add license (Apache 2)
- [x] Check trademark constraints to use "crowdin" references
- [x] Reference to `crowdin` package instead of repository when released on npm, requires hailocab/crowdin-node#1
- [x] Test and document templating option for config

**Comment by PaulLeCam** [comment]
Hey @saulhoward hopefully I fixed the issue you had last time, can you check and confirm if it works for you?
@neelvadgama-hailo @gabor-hailo @alxhill @henriquea @mattheath @kenshiro-o could please review the code before release?
Thanks!

**Comment by saulhoward** [comment]
@PaulLeCam I've successfully tested this on two projects now:
- https://github.com/hailocab/crm-preference-web
- https://github.com/hailocab/lead-web

It works really well! :+1:

**Comment by PaulLeCam** [comment]
@saulhoward Cool, thanks!
